config/routes.rb
HolidayWorkday::Engine.routes.draw do
  resources :hwdays, only: [:index] do
    post :toggle, on: :collection
  end
  root "hwdays#index"
end

app/models/holiday_workday/application_record.rb
module HolidayWorkday
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/holiday_workday/hwday.rb
module HolidayWorkday
  class Hwday < ApplicationRecord
    validates :date, uniqueness: true, presence: true
    enum day_type: %i[holiday workday]
    before_create :set_day_type

    def self.workdays(range)
      workday.where(date: range).pluck(:date)
    end

    def self.holidays(range)
      holiday.where(date: range).pluck(:date)
    end

    def self.worked_days(range)
      range.reject{|x| x.sunday? || x.saturday?} - holidays(range) + workdays(range)
    end

    def self.weeks(range)
      weeks = []
      week_start = range.first
      return weeks if week_start > range.last

      week_end = week_start.at_end_of_week
      loop do
        break if week_start > range.last

        week_end = range.last if week_end > range.last
        week = (week_start..week_end).to_a
        weeks << week
        break if week_end == range.last

        week_start = week_end.next_day
        week_end = week_start.end_of_week
      end
      weeks
    end

    def self.workday_weeks(range)
      weeks = []
      week_start = range.first
      workdays = workdays(range)
      holidays = holidays(range)
      return weeks if week_start > range.last

      week_end = week_start.at_end_of_week
      loop do
        break if week_start > range.last

        week_end = range.last if week_end > range.last
        weekends, week = (week_start..week_end).partition { |x| x.sunday? || x.saturday? }

        week = week - holidays + (weekends & workdays)
        weeks << week if week.present?
        break if week_end == range.last
        week_start = week_end.next_day
        week_end = week_start.end_of_week
      end
      weeks
    end

    def weekend?
      date.saturday? || date.sunday?
    end

    private

    def set_day_type
      self.day_type = weekend? ? :workday : :holiday
    end
  end
end

app/controllers/holiday_workday/application_controller.rb
module HolidayWorkday
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/holiday_workday/hwdays_controller.rb
require_dependency 'holiday_workday/application_controller'

module HolidayWorkday
  class HwdaysController < ApplicationController
    def index
      @current_year = params[:year] ? Date.parse(params[:year]) : Date.current.at_beginning_of_year
      range = (@current_year..@current_year.at_end_of_year)
      @holidays = Hwday.holidays(range)
      @workdays = Hwday.workdays(range)
    end

    ##
    # POST /holiday_workday/toggle
    def toggle
      @holiday_workday = Hwday.find_by(date: params[:date])
      if @holiday_workday
        @holiday_workday.destroy
      else
        date = Date.parse(params[:date])
        @holiday_workday = Hwday.workday.create(date: date)
      end
    rescue StandardError => e
      @e = e
      render 'error.js.erb'
    end
  end
end

app/helpers/holiday_workday/application_helper.rb
module HolidayWorkday
  module ApplicationHelper
  end
end

app/helpers/holiday_workday/hwdays_helper.rb
module HolidayWorkday
  module HwdaysHelper
    def day_class(date)
      return '' unless date

      return 'bg-warn' if @workdays.include?(date)
      return 'bg-primary' if @holidays.include?(date)
      return 'text-primary' if date.saturday? || date.sunday?
    end

    def toggle_date_class(holiday_workday)
      if holiday_workday.destroyed?
        holiday_workday.weekend? ? 'text-primary' : ''
      else
        holiday_workday.holiday? ? 'bg-primary' : 'bg-warn'
      end
    end
  end
end

app/views/holiday_workday/hwdays/error.js.erb
alert("<%=raw @e.message.tr("\n", ",") %>")

app/views/holiday_workday/hwdays/index.html.erb
<div class=''>
  <div class=''>
    <div class=''>
      <h1 class=''><%= t('holiday_workday.label_holiday_workday') %></h1>
      <span class="holiday"></span><span><%= t('holiday_workday.label_holiday') %></span>
      <span class="workday"></span><span><%= t('holiday_workday.label_workday') %></span>
    </div>
  </div>
</div>
<h1 class='year'>
<span><%= link_to '<', hwdays_path(year: @current_year.prev_year), class: 'year-nav' %><span>
<span><%= @current_year.year %><%= t('holiday_workday.label_year')%></span>
<span><%= link_to '>', hwdays_path(year: @current_year.next_year), class: 'year-nav' %><span>
</h1>
<% (1..12).each do |i| %>
<% begin_month = Date.parse("#{@current_year.year}-#{i}-1") %>
<div class="calendar">
  <table>
    <caption><%=t("holiday_workday.month.#{i}") %></caption>
    <thead>
      <tr>
        <th><%= t('holiday_workday.monday') %></th>
        <th><%= t('holiday_workday.tuesday') %></th>
        <th><%= t('holiday_workday.wednesday') %></th>
        <th><%= t('holiday_workday.thursday') %></th>
        <th><%= t('holiday_workday.friday') %></th>
        <th><%= t('holiday_workday.saturday') %></th>
        <th><%= t('holiday_workday.sunday') %></th>
      <tr>
    </thead>
    <tbody>
      <% HolidayWorkday::Hwday.weeks(begin_month..begin_month.at_end_of_month).each_with_index do |week, i| %>
      <% if i == 0 && week.size < 7 %>
      <% week.unshift(*Array.new(7 - week.size, nil)) %>
      <% end %>
      <tr>
        <% week.each do |date| %>
        <td title="<%= t('holiday_workday.day_title')%>" data-date="<%= date %>">
        <% if date %>
          <%= link_to date.day, toggle_hwdays_path(date: date), method: 'post', remote: true, class: day_class(date) %>
        <% end %>
        </td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>

app/views/holiday_workday/hwdays/toggle.js.erb
$("[data-date='<%= @holiday_workday.date %>']").find('a')[0].classList = ['<%= toggle_date_class(@holiday_workday)%>']

app/views/layouts/holiday_workday/_loading.html.erb
<div class="spinner-wrapper hide">
  <div class="lds-spinner">
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    </div>
</div>

app/views/layouts/holiday_workday/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HolidayWorkday</title>
  <%= stylesheet_link_tag    "holiday_workday/application", media: "all" %>
  <%= javascript_include_tag "holiday_workday/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>